[build]
  functions = "netlify/functions"
  command = "npm run build"  # optional, if you have build scripts

[functions]

  [functions.background_timeout]
  # timeout in seconds
  seconds = 900

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

  [plugins.inputs]
    function = "handler"
    schedule = "*/15 * * * *"
