name: Update Proxies

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run proxy update script
        run: node scripts/update-proxies.mjs

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add proxies.txt
          git diff --cached --quiet || git commit -m "Update proxies.txt"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SilkArt/combinedvpn.git HEAD:main
